sonar_health_metrics:
  - bugs 
  - new_bugs
  - reliability_rating
  - vulnerabilities
  - new_vulnerabilities
  - security_rating
  - code_smells
  - new_code_smells
  - sqale_rating
  - dupilicated_lines_density
  - lines_of_code
  - complexity
  - comments_lines_density
  - violations
  - new_violations
  - sqale_index

sonar_runner_path: /opt/sonar-runner/bin/sonar-runner
